GET http://localhost:3007/todos/ HTTP/1.1

###

GET http://localhost:3007/users/ HTTP/1.1

###

GET http://localhost:3007/users

###

POST http://localhost:3005/todo/new/
Content-Type: application/json

{
"text": "Pick up my gordiniooo"
}

###

POST http://localhost:3007/users/new
Content-Type: application/json

{
"name": "Pick up my gordindodododo",
"textHistory": "gord"
}

###

DELETE http://localhost:3005/todo/delete/

###
PUT http://localhost:3005/todo/update/60e585d86177f95ff0574323 Content-Type: application/json

{
"text": "Go Shopping for Milk"
}
###

PUT GET http://localhost:3007/users/update

{
    "textHistory": "Nov 123"
}

